"""initial_schema

Revision ID: 9305dccddcc8
Revises: 
Create Date: 2026-06-17 23:34:20.877324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9305dccddcc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DATA_SOURCES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DATA_SOURCES_workspace_id'), 'DATA_SOURCES', ['workspace_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('DOCUMENT', 'GIT_COMMIT', 'DB_SCHEMA', name='chunksourcetype'), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=50), nullable=False),
    sa.Column('vector_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_chunks_source', 'document_chunks', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_vector_id'), 'document_chunks', ['vector_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_workspace_id'), 'document_chunks', ['workspace_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_tokens', sa.Numeric(precision=12, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'date', 'embedding_model', name='uq_usage_logs_workspace_date_model')
    )
    op.create_index(op.f('ix_usage_logs_workspace_id'), 'usage_logs', ['workspace_id'], unique=False)
    op.create_table('DATABASE_SCHEMAS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['DATA_SOURCES.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DATABASE_SCHEMAS_workspace_id'), 'DATABASE_SCHEMAS', ['workspace_id'], unique=False)
    op.create_table('GIT_COMMITS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['DATA_SOURCES.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'commit_hash', name='uq_git_commits_workspace_hash')
    )
    op.create_index(op.f('ix_GIT_COMMITS_commit_hash'), 'GIT_COMMITS', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_GIT_COMMITS_workspace_id'), 'GIT_COMMITS', ['workspace_id'], unique=False)
    op.create_table('KNOWLEDGE_DOCUMENTS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['DATA_SOURCES.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_KNOWLEDGE_DOCUMENTS_workspace_id'), 'KNOWLEDGE_DOCUMENTS', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_KNOWLEDGE_DOCUMENTS_workspace_id'), table_name='KNOWLEDGE_DOCUMENTS')
    op.drop_table('KNOWLEDGE_DOCUMENTS')
    op.drop_index(op.f('ix_GIT_COMMITS_workspace_id'), table_name='GIT_COMMITS')
    op.drop_index(op.f('ix_GIT_COMMITS_commit_hash'), table_name='GIT_COMMITS')
    op.drop_table('GIT_COMMITS')
    op.drop_index(op.f('ix_DATABASE_SCHEMAS_workspace_id'), table_name='DATABASE_SCHEMAS')
    op.drop_table('DATABASE_SCHEMAS')
    op.drop_index(op.f('ix_usage_logs_workspace_id'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_document_chunks_workspace_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_vector_id'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_source', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_DATA_SOURCES_workspace_id'), table_name='DATA_SOURCES')
    op.drop_table('DATA_SOURCES')
    # ### end Alembic commands ###
